# Generated by Django 6.0.4 on 2026-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
